// Contenido de los 10 caminos — basado en "Cómo escuchar al Espíritu" de Guillermo Ameche
// Las oraciones inicial / final / a María son tradicionales / litúrgicas;
// las narraciones bíblicas son texto bíblico público; los comentarios son síntesis propia.
// Para el desarrollo COMPLETO de cada camino, abre el libro original desde el botón "Texto original".
window.CAMINOS = [
  {
    id: 'abraham',
    numero: 1,
    nombre: 'Abraham',
    subtitulo: 'El camino de la fe',
    versiculo: 'Camina en mi presencia hasta alcanzar la perfección. — Gen 17,1',
    color: '#c97b50',
    pdfPage: 4,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Dios, mi creador y mi eterno acompañante, Tú que eres fuente de todo lo que soy y de lo que pueda ser, ayúdame a escucharte cuando me llamas para que pueda andar contigo hasta encontrar una vida mejor para mí y para todo mi pueblo. Te lo pido por tu Hijo, Jesucristo. Amén.',
    introduccion: 'Casi todos creemos en algo. La fe bíblica, sin embargo, no es creer en algo, sino creer en ALGUIEN — alguien vivo que nos llama personalmente y nos invita a caminar con él hasta una vida más plena. Ese alguien es Dios, fuente y motor de toda vida.\n\nEsta fe no es estática. Es un caminar. Empieza con un llamado interior, sigue con un paso valiente y se sostiene en la confianza de que quien nos llama nos acompaña. En la Biblia esta experiencia aparece por primera vez con claridad en Abraham, un pastor seminómada del segundo milenio antes de Cristo que oyó la voz del Dios vivo y le creyó.\n\nEn este primer camino aprenderemos a reconocer en nosotros ese mismo llamado: a distinguir cuándo lo que sentimos por dentro es el Dios que nos invita a caminar, y cuándo es solo costumbre, miedo o búsqueda de seguridad. Por eso la fe de Abraham es la puerta: si no aprendemos primero a CREER en alguien que nos habla, todo lo demás del discernimiento queda en el aire.',
    historia: 'Abram nació hace casi 4 mil años en Ur de los caldeos, en lo que hoy es Irak. Su familia eran pastores seminómadas — gente humilde, mal vista por los habitantes de las ciudades, pero querida por Dios.\n\nUn día, cuando los pastos escaseaban y el grupo tenía que tomar una decisión, Abram escuchó por dentro una voz: «Sal de tu tierra, de tu parentela y de la casa de tu padre, hacia la tierra que yo te mostraré. Yo haré de ti una nación grande, te bendeciré y engrandeceré tu nombre, y serás una bendición» (Gen 12,1-2).\n\nAbram tuvo miedo. Dejar lo conocido — la tierra, los parientes, las costumbres — daba vértigo. Pero descubrió algo: cada vez que pensaba en quedarse, lo invadía una insatisfacción profunda; cada vez que pensaba en ir, sentía una paz honda. Esa paz fue su brújula. Tomó a Saray, su esposa, a Lot, su sobrino, a sus rebaños y servidores, y partió.\n\nEl camino fue largo. Pasó por Harán, donde murió su padre Téraj. Llegó a Canaán y allí Dios le mostró la tierra prometida. Bajó a Egipto huyendo del hambre. Volvió. Se separó de Lot dejándolo elegir primero la mejor parte. Combatió por rescatar a su sobrino. Recibió la promesa de un hijo cuando ya era viejo y Saray estéril. Se rió de la promesa, dudó, cayó. Y, sin embargo, siguió creyendo. Cuando nació Isaac fue como recibir la vida misma de Dios.\n\nLa prueba más dura vino después: Dios le pidió ofrecer a Isaac, el hijo de la promesa. Abraham caminó tres días al monte Moria con el corazón roto, dispuesto a obedecer. En el último momento, Dios detuvo su mano. Había aprendido lo definitivo: que Dios es Dios de vida, no de muerte. Y que cuando uno se atreve a entregárselo todo, lo recibe todo de vuelta, multiplicado.',
    aplicacion: 'La experiencia de Abraham nos enseña tres cosas concretas para hoy:\n\n1. DIOS NOS LLAMA POR DENTRO. No con voces audibles, sino con sentimientos persistentes. Cuando una opción te llena de paz honda y la otra te deja una insatisfacción que no se calma, Dios te está hablando.\n\n2. LA FE ES CAMINAR, NO QUEDARSE. Creer en Dios no es saber cosas sobre él, es ponerse en movimiento confiando en que va contigo. Si tu fe no te mueve, no es fe bíblica.\n\n3. DIOS ES DIOS DE VIDA. Cuando lo que oyes te lleva a más vida — para ti y para los tuyos — viene de él. Cuando lleva a la muerte, al miedo paralizante, a la destrucción, no viene de él. Esta es la primera prueba de todo discernimiento.\n\n¿Cómo te llamó el Señor a ti? ¿Qué etapa del camino estás viviendo: la de salir, la del desierto, la de la promesa, la de la prueba, la de la entrega?',
    ejercicio: 'Durante los siete días de esta semana, cada noche siéntate dos minutos y registra:\n\n• ¿Qué decisión pendiente tengo en este momento?\n• Cuando pienso en una opción, ¿qué siento por dentro?\n• Cuando pienso en la otra, ¿qué siento?\n• ¿Cuál de las dos me deja más paz honda (no alivio fácil)?\n• ¿Cuál me deja insatisfacción persistente?\n\nAl final de la semana, relee tus notas. Mira hacia dónde te empuja la paz. Probablemente ahí está el llamado.',
    preguntas: [
      '¿En qué área de mi vida me está pidiendo Dios que "salga" de algo conocido?',
      '¿Qué miedos concretos me detienen?',
      '¿Cuándo en mi vida he sentido esa paz honda al tomar una decisión difícil?',
      '¿Cuándo he sentido la insatisfacción profunda que me decía que algo no era para mí?',
      '¿Quién es Dios para mí: una idea o alguien vivo que me habla?',
      '¿Qué pequeño paso de fe puedo dar esta semana?'
    ],
    salmoNombre: 'Salmo 119 (selección)',
    salmo: 'Tu palabra es lámpara para mis pasos, luz en mi sendero.\nYo te he buscado de todo corazón, no me dejes desviar de tus mandatos.\nEnséñame, Señor, el camino de tus preceptos, y lo guardaré hasta el fin.\nDirige mis pasos según tu palabra, que ninguna iniquidad me domine.\nEl despliegue de tus palabras ilumina, da inteligencia a los sencillos.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'salomon',
    numero: 2,
    nombre: 'Salomón',
    subtitulo: 'Escuchar los sentimientos',
    versiculo: 'Dame, pues, a mí, tu servidor, un corazón que sepa escuchar. — 1 Re 3,9',
    color: '#b8924a',
    pdfPage: 12,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Señor y Dios mío, me has llamado a acompañar a mi pueblo en su lucha por la vida. Sé que me faltan muchas cosas para poder amarlo y servirlo bien. Pero sé también que tú me conoces y que me acompañas. Por eso, Señor, te pido que me des un espíritu atento para escuchar, para comprender y para actuar con rectitud. Amén.',
    introduccion: 'Con Abraham aprendimos que Dios nos llama. Pero, ¿en qué idioma habla? La respuesta de la tradición bíblica es clara y desconcertante: Dios habla en el idioma de los SENTIMIENTOS. No en ideas abstractas, no en mandatos por escrito, sino en el movimiento interior del corazón.\n\nPor eso el segundo paso es aprender a escuchar lo que sentimos — todos los sentimientos, sin censurarlos ni avergonzarnos de ellos. Es justo lo que pide Salomón al empezar su reinado: «un corazón que sepa escuchar». No pide riqueza, ni victoria, ni vida larga. Pide oído interior. Y Dios le concede sabiduría porque pidió lo único que abre la puerta a todo lo demás.\n\nEsta semana practicaremos lo más básico y lo más difícil del camino espiritual: notar lo que pasa por dentro y nombrarlo. Sin esa práctica, todo el resto del discernimiento es imposible — no se puede discernir lo que no se siente.',
    historia: 'Salomón fue hijo de David y Betsabé. Subió al trono muy joven, casi un adolescente, y heredó un reino complicado. La noche en que asumió el poder, Dios se le apareció en sueños en Gabaón y le dijo: «Pídeme lo que quieras y te lo daré».\n\nSalomón respondió con humildad: «Señor, soy un muchacho joven, no sé cómo conducirme. Tu siervo está en medio de un pueblo numeroso. Da, pues, a tu siervo un corazón que sepa escuchar para gobernar a tu pueblo, para discernir entre el bien y el mal» (1 Re 3,7-9).\n\nA Dios le agradó tanto la petición que le concedió la sabiduría pedida y, además, lo que no había pedido: riqueza y honor.\n\nLa fama de su sabiduría se hizo legendaria con el famoso juicio de las dos mujeres. Dos prostitutas vivían en la misma casa. Las dos habían dado a luz, pero un niño murió. Cada una decía que el vivo era suyo. Llevaron el caso al rey. No había testigos. ¿Cómo distinguir la verdad?\n\nSalomón ordenó: «Tráiganme una espada. Partan en dos al niño vivo y denle una mitad a cada una». Quería ver qué SENTÍA cada mujer. La verdadera madre, removidas sus entrañas, dijo: «¡Por favor, señor mío! Denle a ella el niño vivo, pero no lo maten». La otra, fría, dijo: «Que no sea ni mío ni tuyo. ¡Pártanlo!» Salomón dictó sentencia: «Denle el niño a la primera. Esa es su madre». No la descubrió por palabras, sino por sentimientos. Donde había amor verdadero, ahí estaba la verdad.\n\nLa lección quedó para siempre: para no ser engañados por discursos, ideas o argumentos, hay que escuchar lo que la gente realmente siente. Porque ahí — en los sentimientos — habla el Dios vivo.',
    aplicacion: 'De la sabiduría de Salomón se desprenden cuatro principios prácticos:\n\n1. LOS SENTIMIENTOS SON LENGUAJE. No son obstáculos para la vida espiritual; son su material. Lo que sientes hoy es donde Dios te habla hoy.\n\n2. NO SE CENSURAN. La regla de oro del discernimiento ignaciano es: ningún sentimiento es "malo en sí". Lo que importa no es sentirlo, sino qué hago con él. Reprimirlo o avergonzarlo no funciona; nombrarlo, sí.\n\n3. NO SE JUZGAN AL MOMENTO. Primero escucha; después analiza. La prisa por interpretar mata la escucha.\n\n4. SE NOMBRAN CON PRECISIÓN. La diferencia entre "estoy mal" y "estoy decepcionado, además de cansado y un poco enojado conmigo mismo" es enorme. Cuanto más fino el nombre, más claro el camino.',
    ejercicio: 'Cada noche de esta semana, dedica dos minutos a escribir:\n\n• El sentimiento que más se repitió hoy.\n• Una situación concreta donde apareció.\n• Una palabra precisa que lo nombre (no «mal», sino «celos», «alivio», «vergüenza», «ternura»).\n\nNo lo juzgues. No le busques causa todavía. Solo nómbralo. La práctica es la base de todos los caminos siguientes.',
    preguntas: [
      '¿Qué sentimientos me cuesta más reconocer en mí?',
      '¿Cuál censuro o me avergüenza sentir?',
      '¿En qué momento del día me cuesta más estar atento a lo que siento?',
      '¿Quién en mi vida me ha enseñado a escuchar?',
      '¿Pido yo, como Salomón, "un corazón que sepa escuchar" o pido otras cosas?',
      '¿Cómo distingo cuando alguien me habla con la cabeza y cuando me habla desde el corazón?'
    ],
    salmoNombre: 'Proverbios 8 (selección)',
    salmo: 'Yo, la Sabiduría, habito con la prudencia, y poseo ciencia y reflexión.\nMío es el consejo y la sensatez, mía la inteligencia, mía la fuerza.\nA los que me aman, los amo, y los que me buscan, me encuentran.\nDichoso el hombre que me escucha, velando ante mi puerta cada día.\nQuien me halla a mí, halla la vida y alcanza el favor del Señor.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'esther',
    numero: 3,
    nombre: 'Ester',
    subtitulo: 'Comprender y actuar con rectitud',
    versiculo: 'Iré a ver al rey, aunque sea contra la ley. Y si he de morir, moriré. — Ester 4,16',
    color: '#a85a7a',
    pdfPage: 20,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Padre mío y Señor mío, tú conoces bien todo lo que siento en mi corazón. Sabes cuándo actúo libremente y cuándo no. Ayúdame a comprender tu voluntad con claridad para que pueda hacerla con gusto, para bien mío y de todo tu pueblo. Líbrame de los miedos y de todo lo que no me deje ni vivir ni servir a los demás. Te lo pido por tu Hijo, Jesucristo. Amén.',
    introduccion: 'Salomón nos enseñó a escuchar los sentimientos. Pero escuchar no basta. Hay que COMPRENDER hacia dónde nos llevan, y luego ACTUAR con rectitud. Ese es el aporte de Ester.\n\nLa joven judía, convertida en reina del imperio persa, enfrenta el momento decisivo de su vida bajo dos sentimientos contrarios: el miedo de morir si se presenta sin ser llamada ante el rey, y el amor por su pueblo amenazado de exterminio. Comprende lo que cada sentimiento le pide y elige.\n\nEste tercer paso es donde se concreta el discernimiento. La pregunta deja de ser «¿qué siento?» y pasa a ser «¿qué pide de mí lo que siento?». No todo sentimiento debe ser obedecido — el miedo, por ejemplo, casi siempre nos pide huir, y casi siempre tenemos que ir contra él. Pero todo sentimiento debe ser COMPRENDIDO, porque es donde Dios traza el mapa.\n\nDos miedos atrapan al cristiano: fallar ante Dios (ser castigado) y ser rechazado por los demás (perder el lugar). Mientras esos dos miedos no se enfrenten, no se actúa con libertad.',
    historia: 'Después de los grandes profetas, Israel fue conquistado por Babilonia, y luego pasó a manos de los persas. Muchos judíos quedaron dispersos por todo el imperio.\n\nEn la corte del rey Asuero (Jerjes), una joven judía huérfana llamada Hadasá — Ester en persa — fue elegida reina por su belleza, después de que la reina Vasti fuera repudiada. Su tío Mardoqueo, que la había criado, le aconsejó ocultar su origen judío.\n\nMardoqueo trabajaba a las puertas del palacio. Un día se negó a postrarse ante Amán, el primer ministro orgulloso. Amán, ofendido, decidió no solo matar a Mardoqueo sino exterminar a TODO el pueblo judío del imperio. Convenció al rey y se promulgó el decreto.\n\nMardoqueo se vistió de luto, se rasgó las vestiduras, gritó por las calles. Llegó el aviso a Ester. Mardoqueo le mandó decir: «No creas que te salvarás tú por estar en el palacio. Si te callas, la salvación vendrá por otro lado, pero tú y tu casa pereceréis. ¿Y quién sabe si has llegado a ser reina precisamente para un momento como este?» (Est 4,13-14).\n\nEster sintió por dentro la lucha. Si se presentaba sin ser llamada, la ley persa la condenaba a muerte salvo que el rey extendiera su cetro. Tenía miedo. Mucho miedo. Pero también amaba a su pueblo. Comprendió:\n\n— Si callo y me protejo: salvo mi vida, pero dejo morir a los míos. Y voy a vivir destrozada por dentro.\n— Si hablo y arriesgo: puedo morir, pero salvo a mi pueblo. Y mi corazón estará en paz.\n\nEligió hablar. Pidió tres días de ayuno a todos los judíos de Susa. Se preparó. Y dijo la frase que la define: «Iré ante el rey aunque sea contra la ley. Y si he de morir, moriré».\n\nEntró. El rey extendió el cetro. Ester habló con prudencia, en dos banquetes, hasta desenmascarar a Amán. Amán fue ahorcado en la horca que había preparado para Mardoqueo. El pueblo se salvó. La fiesta de Purim recuerda hasta hoy aquel día.',
    aplicacion: 'Ester nos da el método de tres pasos para hallar la voluntad de Dios:\n\n1. ESCUCHAR todos los sentimientos sin censurar ninguno (incluido el miedo).\n2. COMPRENDER hacia dónde lleva cada uno: qué se gana y qué se pierde con cada uno; qué tipo de persona me hago siguiéndolo; cuál es la motivación de fondo.\n3. ACTUAR CON RECTITUD: por amor, no por miedo, y con paz en el corazón.\n\nDios nunca pide que actuemos por miedo. Solo pide que actuemos por amor. Y siempre que actuamos por amor — aunque sea costoso — el corazón queda en paz, aunque la cabeza tenga dudas.\n\nLa prueba final del discernimiento: ¿qué motivación me mueve, miedo o amor? ¿qué sensación me deja, agitación o paz?',
    ejercicio: 'Al cierre de la semana, relee tu registro de sentimientos. Identifica el más persistente — esa repetición es donde Dios te está llamando a mirar.\n\nLuego pregúntale a ese sentimiento, una por una:\n• ¿Qué ganaría si lo sigo? ¿Qué perdería?\n• ¿Qué tipo de persona me vuelvo si lo sigo?\n• ¿Qué me motiva — amor o miedo?\n• Si hago esto, ¿siento paz honda o solo alivio momentáneo?\n\nSi la motivación es amor y la sensación es paz: vas por donde Dios quiere. Si la motivación es miedo y la sensación es agitación: revisa.',
    preguntas: [
      '¿Cuál es mi miedo más grande hoy: fallar ante Dios o ser rechazado por los demás?',
      '¿En qué decisión actual estoy entre el miedo y el amor?',
      '¿Qué pierdo si callo y qué gano si hablo?',
      '¿He sentido alguna vez esa "paz aunque tenga miedo" que solo da el amor?',
      '¿Estoy en un momento como el de Ester — "para esto has llegado"?',
      '¿Qué pequeña Ester puedo ser esta semana en mi entorno?'
    ],
    salmoNombre: 'Salmo 121',
    salmo: 'Levanto mis ojos a los montes: ¿de dónde me vendrá el auxilio?\nMi auxilio viene del Señor, que hizo el cielo y la tierra.\nNo permitirá que resbale tu pie, tu guardián no duerme.\nEl Señor te guarda a su sombra, está a tu derecha.\nDe día el sol no te hará daño, ni la luna de noche.\nEl Señor te guarda de todo mal, él guarda tu alma.\nEl Señor guarda tus entradas y salidas, ahora y por siempre.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'amos',
    numero: 4,
    nombre: 'Amós',
    subtitulo: 'Visión profética: ver más allá de lo mío',
    versiculo: 'Que el derecho corra como agua, y la justicia como un torrente inagotable. — Amós 5,24',
    color: '#7a8a4a',
    pdfPage: 30,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Padre, ayúdame a descubrir tu voz en todo lo que sucede en mi pueblo. Desde ahí me hablas. Y ahí te quiero escuchar para que seas tú quien me oriente a caminar junto con mis hermanos hacia esta vida mejor que nos has prometido desde Abraham hasta nuestros días. Te lo pido por tu Hijo, Jesucristo. Amén.',
    introduccion: 'Abraham, Salomón y Ester se sentían llamados a hacer algo por su pueblo, y descubrieron qué hacer fijándose en lo que pasaba a su alrededor. Pero sus respuestas fueron distintas: Abraham salió, Salomón se calló y juzgó, Ester habló. No hay receta única — hay realidades concretas a las que responder.\n\nLos profetas son los hombres y mujeres con sensibilidad para escuchar la voz de Dios EN LA VIDA DEL PUEBLO. No la oyen en abstracciones; la oyen en el grito del que sufre, en la mentira institucional, en la injusticia disfrazada de ley.\n\nAmós es el primero de los profetas escritores. Pastor sencillo de Tecua, sin formación religiosa oficial, fue arrancado por Dios de su rebaño para denunciar el orden corrupto de su tiempo. Lo que vio era invisible para los demás porque los demás miraban hacia otro lado.\n\nEste cuarto camino nos enseña a sacar la mirada de "lo mío" — mis emociones, mi vida espiritual, mis pequeños progresos — y dirigirla a la realidad social donde Dios sigue hablando hoy.',
    historia: 'Amós vivió en el siglo VIII a.C., bajo el rey Jeroboán II. El reino del norte de Israel atravesaba un momento de prosperidad económica: comercio próspero, ciudades amuralladas, casas de marfil, templos suntuosos en Betel y Dan, fiestas religiosas multitudinarias.\n\nPero por debajo de la prosperidad, la sociedad estaba podrida. Los ricos compraban tierras a precio de hambre. Los jueces se vendían por un par de sandalias. Las balanzas estaban manipuladas. Los pobres eran esclavizados por deudas mínimas. Y todo eso convivía con un culto exterior brillante: incienso, sacrificios, peregrinaciones, cantos.\n\nAmós era pastor en Tecua, en Judá. Cuidaba ganado y cultivaba higos. No era profeta de oficio. Pero un día Dios lo agarró: «El león ruge: ¿quién no temerá? El Señor habla: ¿quién no profetizará?» (Am 3,8).\n\nFue al santuario real de Betel — el más prestigioso del reino — y empezó a hablar. Dios decía por su boca: «Detesto, rechazo sus fiestas; no tolero sus reuniones solemnes. Si me ofrecen holocaustos, no me agradan. Aparten de mí el ruido de sus cantos, no quiero oír el sonido de sus arpas. Que el derecho corra como agua, y la justicia como un torrente inagotable» (Am 5,21-24).\n\nEl sacerdote de Betel, Amasías, lo denunció al rey y le ordenó volverse a Judá: «Vidente, vete, huye a la tierra de Judá; come allí tu pan y profetiza allí. Pero en Betel no vuelvas a profetizar, porque es santuario del rey» (Am 7,12-13).\n\nAmós respondió: «No soy profeta ni hijo de profeta; soy pastor y cultivador de sicomoros. El Señor me sacó de detrás del rebaño y me dijo: ve y profetiza a mi pueblo Israel» (Am 7,14-15).\n\nLo expulsaron. Pero su voz quedó. Pocas décadas después, Israel cayó bajo Asiria, y todo lo que Amós había anunciado se cumplió. Su libro quedó en la Biblia para siempre.',
    aplicacion: 'Amós nos enseña tres verdades incómodas:\n\n1. DIOS HABLA EN LA VIDA DEL PUEBLO, especialmente en quienes sufren. Si tu fe te hace insensible al dolor de los demás, no es fe verdadera — es religión.\n\n2. EL CULTO SIN JUSTICIA ES OFENSIVO PARA DIOS. Las ceremonias religiosas no compensan la injusticia social; al contrario, la disfrazan, y eso le repugna. La medida real de la fe no es lo que cantamos en el templo, sino cómo tratamos al débil fuera de él.\n\n3. LA VOZ PROFÉTICA INCOMODA. Si nuestra fe nunca incomoda a nadie, probablemente no es profética. Pero también: si solo incomoda y nunca consuela, probablemente no es de Dios.\n\nLa pregunta de Amós para hoy: ¿qué injusticia cercana a mí estoy mirando hacia otro lado? ¿qué grito no estoy queriendo oír?',
    ejercicio: 'Esta semana, elige una situación de injusticia o sufrimiento en tu entorno cercano — familia, trabajo, vecindario, ciudad. No la lejana de las noticias; una a la que puedas tocar.\n\nDurante siete días:\n• Ponle nombre concreto.\n• Pregúntate qué sientes al verla (rabia, vergüenza, tristeza, indiferencia, deseo de huir).\n• Escucha qué te dice Dios a través de ese sentimiento.\n• Identifica un paso real, por pequeño que sea, que puedas dar.',
    preguntas: [
      '¿Qué injusticia cercana he estado evitando mirar?',
      '¿Cómo distingo en mí la indignación que viene de Dios y la que viene del ego?',
      '¿Mi vida religiosa me hace más sensible o más insensible al dolor ajeno?',
      '¿Qué "Betel" — qué institución cómoda — me cuesta criticar aunque vea lo que pasa?',
      '¿Quién es para mí hoy el rostro del que sufre?',
      '¿Qué paso pequeño y real puedo dar esta semana?'
    ],
    salmoNombre: 'Salmo 40 (selección)',
    salmo: 'Esperé en el Señor con esperanza, se inclinó hacia mí y escuchó mi clamor.\nMe sacó de la fosa fatal, de la charca fangosa; afianzó mis pies sobre roca.\nSacrificio y ofrenda no quisiste, pero me has dado un oído atento.\nNo exigiste holocausto ni víctima expiatoria; entonces dije: «Aquí estoy, vengo a hacer tu voluntad».',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'elias',
    numero: 5,
    nombre: 'Elías',
    subtitulo: 'Las reglas del discernimiento',
    versiculo: 'No estaba el Señor en el viento huracanado, ni en el terremoto, ni en el fuego. Después del fuego, un susurro de brisa suave. — 1 Re 19,11-12',
    color: '#5a7090',
    pdfPage: 40,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Padre bueno, tu Espíritu me ha tomado de la mano y me hace crear tu reino junto contigo. Ayúdame, Padre, a reconocer la voz de tu Espíritu en mi vida para que podamos hacer juntos tu voluntad. Te lo pido por tu Hijo, Jesucristo. Amén.',
    introduccion: 'Hasta aquí hemos aprendido que Dios nos llama (Abraham), que nos habla en sentimientos (Salomón), que esos sentimientos se comprenden y se actúa por amor (Ester) y que su voz suena especialmente en la vida del pueblo (Amós). Ahora llega la pregunta más fina del camino espiritual: ¿cómo distingo, dentro de lo que siento, lo que viene del Espíritu de Dios y lo que viene del espíritu del mal?\n\nPorque sí: hay dos espíritus actuando dentro de cada uno. Uno construye, el otro destruye. Uno da vida, el otro se la roba. Y los dos hablan en idioma de sentimientos. Aprender a distinguirlos es lo que la tradición espiritual cristiana llama "discernimiento de espíritus".\n\nElías, el primero de los grandes profetas, es quien recibe en el monte Horeb la lección fundamental: Dios no está en lo aparatoso, sino en lo suave. Su voz es susurro, no terremoto. Y san Ignacio de Loyola, muchos siglos después, sistematizará en sus "reglas de discernimiento" lo que Elías vivió.',
    historia: 'Elías el tisbita vivió en el siglo IX a.C. bajo el rey Ajab y la reina fenicia Jezabel, que había impuesto el culto a Baal y perseguía a los profetas del Señor. Elías, solo, los desafió.\n\nEn el monte Carmelo organizó la prueba: 450 profetas de Baal contra él. Cada bando prepararía un sacrificio sin fuego, y el dios verdadero respondería con fuego. Los de Baal gritaron, danzaron y se cortaron desde la mañana hasta la tarde. Nada. Elías oró brevemente, y bajó fuego del cielo que consumió el sacrificio empapado en agua. El pueblo gritó: «¡El Señor es Dios!» Mandó matar a los profetas de Baal.\n\nPero Jezabel no se rindió. Juró matarlo en 24 horas. Y Elías — el profeta del fuego — huyó al desierto, agotado, deprimido, sin querer vivir más. Se acostó bajo una retama y pidió morir: «Basta, Señor. Quítame la vida; no soy mejor que mis padres» (1 Re 19,4).\n\nDurmió. Un ángel lo despertó dos veces y le dio pan y agua. Con esa fuerza caminó cuarenta días y cuarenta noches hasta el monte Horeb — el Sinaí, el monte donde Moisés había recibido la Ley. Allí se metió en una cueva.\n\nLa palabra del Señor le llegó: «¿Qué haces aquí, Elías?». Él respondió quejándose de su soledad y de su fracaso. Dios le dijo: «Sal y ponte de pie en la montaña ante el Señor».\n\nY pasó el Señor. Pasó un viento huracanado que hendía las montañas y rompía las rocas — pero el Señor no estaba en el viento. Después del viento, un terremoto — pero el Señor no estaba en el terremoto. Después del terremoto, un fuego — pero el Señor no estaba en el fuego. Después del fuego, una brisa tenue, un susurro de aire suave. Cuando Elías lo oyó, se cubrió la cara con el manto y salió a la entrada de la cueva. Y entonces sí, Dios le habló (1 Re 19,11-13).\n\nEsa es la lección de Horeb: Dios no se manifiesta en lo aparatoso ni lo violento. Habla en lo sutil, en lo callado, en la paz. Si una "voz" interior te empuja con prisa, agitación, ansiedad o ruido, no es de él.',
    aplicacion: 'Las SEIS REGLAS clásicas del discernimiento — Elías + Ignacio:\n\n1. DOS ESPÍRITUS actúan en ti. El Espíritu de Dios trae vida, paz, amor, libertad, esperanza, ganas de servir. El espíritu del mal trae desesperación, miedo, agitación, encierro, vergüenza paralizante.\n\n2. SI VAS POR BUEN CAMINO, el espíritu malo te agita: te llena de dudas, te desanima, te asusta. El Espíritu Bueno te confirma con paz, valor y ánimo.\n\n3. SI VAS POR MAL CAMINO, el espíritu malo te calma con falsa tranquilidad para mantenerte donde estás. El Espíritu Bueno, en cambio, te incomoda — te causa inquietud para que cambies. Por eso la inquietud no siempre es mala: a veces es exactamente Dios.\n\n4. CONSOLACIÓN es todo movimiento interior hacia más amor: paz honda, alegría serena, lágrimas de gratitud, ganas de servir, fe acrecentada, esperanza viva. Viene de Dios.\n\n5. DESOLACIÓN es todo movimiento contrario: tristeza turbia, agitación, falta de esperanza, ganas de dejarlo todo, atracción a lo bajo. Viene del enemigo. Regla de oro: en desolación NUNCA tomes decisiones nuevas. Mantén lo decidido en consolación. Ora más, no menos. Habla con un acompañante. Recuerda que pasará.\n\n6. DIOS HABLA EN SUSURRO, no en el viento huracanado. Si una voz interior te empuja con prisa, agitación, ansiedad, presión por decidir YA — no es de Dios. La voz de Dios deja tiempo, deja paz, deja libertad.',
    ejercicio: 'Esta semana, cada noche identifica si tu día estuvo dominado por CONSOLACIÓN o por DESOLACIÓN.\n\nSi estuviste en consolación: agradece, no te creas más espiritual de lo que eres, y prepárate para los días grises (van a venir).\n\nSi estuviste en desolación:\n• No tomes decisiones nuevas.\n• Mantén tus rutinas — oración, ejercicio, sueño.\n• Aumenta un poco la oración (no la disminuyas, que es lo que el enemigo busca).\n• Habla con alguien de confianza.\n• Recuerda concretamente cuándo estuviste en consolación: pasará otra vez.',
    preguntas: [
      '¿Estoy hoy en consolación o en desolación?',
      '¿Qué voces internas me empujan con prisa o agitación?',
      '¿Qué decisiones he tomado en desolación que tendría que revisar?',
      '¿Qué "viento, terremoto y fuego" — qué cosas aparatosas — confundo a veces con Dios?',
      '¿Dónde está el "susurro" en mi vida que normalmente no escucho?',
      '¿Quién es mi "ángel bajo la retama" — quién me da pan y agua cuando estoy agotado?'
    ],
    salmoNombre: 'Salmo 143 (selección)',
    salmo: 'Señor, escucha mi oración, presta oído a mi súplica.\nResponde a tu fiel por tu lealtad, por tu justicia.\nNo entres en juicio con tu siervo, pues ningún viviente es justo ante ti.\nMedito todas tus acciones, considero las obras de tus manos.\nHazme saber tu camino, levanto mi alma a ti.\nEnséñame a hacer tu voluntad, porque tú eres mi Dios.\nQue tu buen Espíritu me guíe por tierra llana.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'pablo',
    numero: 6,
    nombre: 'Pablo',
    subtitulo: 'Mirarse con la mirada de Jesús',
    versiculo: 'Te basta mi gracia: la fuerza se realiza en la debilidad. — 2 Cor 12,9',
    color: '#7a4a8a',
    pdfPage: 50,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Dios, concédeme la SERENIDAD para aceptar las cosas que no puedo cambiar, el VALOR para cambiar aquellas que puedo, y la SABIDURÍA para reconocer la diferencia. (Oración de Reinhold Niebuhr / AA)',
    introduccion: 'Las reglas del discernimiento son útiles, pero hay un obstáculo previo a todas ellas: cómo te miras a ti mismo. Si te miras con dureza, ningún discernimiento avanza, porque la voz que mejor escuchas dentro de ti es la del juez interno, no la de Dios.\n\nPablo es el ejemplo perfecto. Hombre de fe intensa, formado en la mejor tradición farisaica, brillante, recto. Y, sin embargo, cargaba un "aguijón en la carne" que no se le quitaba — una debilidad recurrente — y se desesperaba contra sí mismo. La conversión profunda de Pablo no fue solo dejar de perseguir a los cristianos; fue aprender a MIRARSE como Jesús lo miraba: con amor incondicional, no con dureza. Cuando logró esa mirada, vivió en paz. Antes, no.\n\nEl crecimiento personal — el primero de los cuatro crecimientos del cristiano — depende de esto: si aprendes a mirarte con la mirada amorosa de Jesús, todo cambia. Si no, te quedas atascado por años en peleas internas que ningún esfuerzo resuelve.',
    historia: 'Saulo de Tarso nació en una familia judía de la diáspora, ciudadano romano, formado al estilo riguroso del fariseo Gamaliel en Jerusalén. Era brillante, ardiente y recto. Tan recto que cuando apareció el movimiento de los discípulos de Jesús, lo persiguió sin piedad. Estuvo presente, aprobando, en la lapidación de Esteban. Pidió cartas para ir a Damasco a apresar a más cristianos.\n\nCamino de Damasco, una luz lo derribó del caballo. Una voz le dijo: «Saulo, Saulo, ¿por qué me persigues?» — «¿Quién eres, Señor?» — «Yo soy Jesús, a quien tú persigues» (Hch 9,4-5). Quedó ciego tres días. Lo bautizó Ananías. Su vida cambió.\n\nDe perseguidor pasó a apóstol. Recorrió el imperio fundando comunidades, escribió las cartas más profundas del Nuevo Testamento, fundó la teología cristiana. Pero cargaba algo. Lo llamó «un aguijón en mi carne, un mensajero de Satanás que me hiere» (2 Cor 12,7). No sabemos qué era — algunos creen que una enfermedad, otros una tentación recurrente, otros un rasgo de carácter. Pero le pesaba.\n\nLe rogó al Señor tres veces que se lo quitara. Y la respuesta fue: «Te basta mi gracia: la fuerza se realiza en la debilidad» (2 Cor 12,9). Pablo entendió. Dejó de pelearse con su debilidad y empezó a aceptarla como el lugar donde la gracia se manifestaba. Pasó de mirarse con dureza ("Dios ya no me querrá si no soy perfecto") a mirarse con amor ("soy un vaso de barro, y precisamente por eso el tesoro adentro es claramente de Dios").\n\nEsa fue su segunda conversión. Y desde ahí escribió uno de los textos más amados del cristianismo: el himno al amor de 1 Corintios 13.',
    aplicacion: 'Tu crecimiento personal depende de TU MIRADA sobre ti mismo:\n\n• MIRADA DURA: «No estoy bien. No puedo. No sirvo. Dios ya no me querrá. Tengo que cumplir más para merecer.» → Frustración, desánimo, parálisis. La fuerza del pecado.\n\n• MIRADA AMOROSA DE JESÚS: «Soy un vaso de barro. Tengo límites. Dios me quiere así, hoy. Mi debilidad es donde su fuerza se nota más.» → Paz, libertad, ganas reales de cambiar lo que se pueda. La fuerza del Espíritu.\n\nNo es resignación. No es decir «todo está bien». Es dejar de exigirte una perfección que Dios no te exige, y entrar en la paz desde la cual el verdadero crecimiento es posible.\n\nProtocolo Pablo: cada vez que te sorprendas hablándote duro, detente. Pregúntate: ¿cómo me miraría Jesús ahora mismo? Y respira en esa mirada antes de seguir.',
    ejercicio: 'Esta semana, cada vez que te juzgues con dureza, haz tres cosas:\n\n1. Dilo en voz alta, sin censura: «Me estoy diciendo que…»\n2. Pregúntate: ¿cómo me miraría Jesús en este mismo momento?\n3. Lee despacio 1 Corintios 13,4-8 reemplazando «el amor» por «Jesús» y aplicándolo a su mirada sobre ti.\n\nUna vez al día, mírate al espejo y di en voz alta: «Dios me quiere así, hoy».',
    preguntas: [
      '¿Cuál es mi "aguijón en la carne" — esa debilidad recurrente con la que llevo años peleando?',
      '¿Cuál es la voz dura que me hablo a mí mismo? ¿De quién la aprendí?',
      '¿Creo de verdad que Dios me quiere tal como soy hoy, o solo cuando "me porto bien"?',
      '¿Qué cambiaría en mí si me mirara una semana entera con la mirada de Jesús?',
      '¿Dónde está la "fuerza en la debilidad" en mi vida — qué cosa que parecía fracaso ha sido en realidad gracia?',
      '¿A quién en mi entorno necesito mirar también con esa mirada amorosa?'
    ],
    salmoNombre: 'Salmo 92 (selección) / 1 Cor 13',
    salmo: 'Es bueno dar gracias al Señor y tocar para tu nombre, Altísimo.\nProclamar por la mañana tu misericordia y de noche tu fidelidad.\nMe alegras, Señor, con tus acciones, las obras de tus manos me hacen gritar de júbilo.\n\n«El amor es paciente, es servicial; no es envidioso, no es jactancioso, no se engríe; no es indecoroso, no busca lo suyo, no se irrita, no toma en cuenta el mal; no se alegra de la injusticia, se alegra con la verdad. Todo lo excusa, todo lo cree, todo lo espera, todo lo soporta. El amor no acaba nunca.» (1 Cor 13,4-8)',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'rut',
    numero: 7,
    nombre: 'Rut',
    subtitulo: 'Crecer en comunidad',
    versiculo: 'A donde tú vayas, iré yo. Tu pueblo será mi pueblo, y tu Dios será mi Dios. — Rut 1,16',
    color: '#a07050',
    pdfPage: 60,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Señor, hazme un instrumento de tu paz. Donde haya odio, ponga yo amor; donde haya ofensa, perdón; donde haya discordia, unión; donde haya error, verdad; donde haya duda, fe; donde haya desesperación, esperanza; donde haya tinieblas, luz; donde haya tristeza, alegría. Maestro, que no busque tanto ser consolado como consolar; ser comprendido como comprender; ser amado como amar. Porque dando es como se recibe; olvidando, como se encuentra; perdonando, como se es perdonado; muriendo, como se resucita a la vida eterna. (Oración atribuida a san Francisco de Asís)',
    introduccion: 'Pablo nos enseñó a mirarnos con la mirada de Jesús. Pero nadie crece solo. La fe cristiana es comunitaria desde la raíz: el primer mandamiento del Antiguo Testamento es amar a Dios y la prueba del amor a Dios es amar al prójimo. No hay una sin la otra.\n\nEl crecimiento comunitario es el segundo de los cuatro crecimientos del cristiano. Sin él, el crecimiento personal se vuelve narcisismo espiritual. Y, asombrosamente, también funciona al revés: sin crecimiento personal sano, la comunidad se vuelve dependencia o manipulación.\n\nRut, una mujer extranjera, moabita, viuda, sin hijos, sin tierra, nos enseña qué significa elegir libremente vincularse a un pueblo, a una historia, a un Dios. Su fidelidad a Noemí — su suegra israelita — atraviesa fronteras de sangre, religión y conveniencia. Y por esa fidelidad ella, la extranjera, entra en el linaje del rey David y de Jesús.',
    historia: 'En tiempos de los jueces hubo hambre en Israel. Un hombre de Belén, Elimelec, emigró con su esposa Noemí y sus dos hijos a Moab — territorio considerado pagano. Allí los hijos se casaron con dos mujeres moabitas, Orfa y Rut. Diez años después, Elimelec y los dos hijos murieron, dejando tres viudas sin sostén.\n\nNoemí decidió volver a Belén — había oído que el hambre había terminado. Despidió a sus nueras: «Vayan, vuelva cada una a casa de su madre. Que el Señor las trate con bondad como ustedes me trataron a mí y a mis hijos» (Rut 1,8).\n\nLloraron las tres. Orfa, después de dudar, se volvió a su casa. Pero Rut se aferró a Noemí y dijo las palabras que la inmortalizan:\n\n«No insistas en que te abandone y me separe de ti. A donde tú vayas, iré yo; donde tú vivas, viviré yo. Tu pueblo será mi pueblo, y tu Dios será mi Dios. Donde tú mueras, moriré yo, y allí seré sepultada. Que el Señor me castigue si no es solo la muerte la que me separe de ti» (Rut 1,16-17).\n\nLlegaron a Belén pobres, sin nada. Rut salió a espigar — el derecho del pobre a recoger lo que los segadores dejaban caer. El campo era de Booz, pariente de Elimelec. Booz vio a Rut y preguntó por ella. Le habían contado todo lo que había hecho por su suegra. Le habló con respeto: «Quédate aquí. Que el Señor te recompense; que el Dios de Israel, bajo cuyas alas has venido a refugiarte, te dé una recompensa colmada» (Rut 2,12).\n\nLe dio agua, comida, protección. Ordenó que dejaran caer espigas a propósito. Rut volvió a casa con grano abundante. Noemí entendió, se le llenaron los ojos de lágrimas: el Señor no las había abandonado.\n\nSiguió la historia del derecho del rescate — un pariente cercano debía «redimir» a la viuda, casándose con ella para mantener el nombre del difunto. Booz hizo el rito legal a la puerta de la ciudad y se casó con Rut. Tuvieron un hijo: Obed, padre de Jesé, padre del rey David.\n\nAsí, una moabita extranjera entró en el linaje del Mesías. Su nombre se lee cada año en la fiesta judía de Pentecostés — y, dos veces, en la genealogía de Jesús al inicio del Evangelio.',
    aplicacion: 'Rut nos enseña cuatro verdades sobre el crecimiento comunitario:\n\n1. EL VÍNCULO ES ELECCIÓN. Rut podía haber vuelto a Moab. Eligió quedarse. La comunidad cristiana se construye sobre elecciones libres, no sobre obligaciones de sangre.\n\n2. LA FIDELIDAD SOSTIENE. Cuando todos los demás se van, alguien se queda. Esa lealtad — pequeña, callada, prolongada — es la materia prima de la comunidad real.\n\n3. EL EXTRANJERO TRAE A DIOS. Quien parece más lejano a tu fe puede ser el instrumento más claro del amor de Dios. Rut, la moabita, fue más fiel que muchos hijos de Israel.\n\n4. NADIE CRECE SOLO. Booz protege a Rut, Rut sostiene a Noemí, Noemí guía a Rut, el clan rescata a la familia. La gracia se mueve por relaciones, no por individuos aislados.\n\nLa pregunta concreta: ¿quién es mi Noemí — a quién acompaño cuando todos los demás se han ido? ¿Y quién es mi Booz — quién me ha sostenido sin que yo se lo mereciera?',
    ejercicio: 'Esta semana, identifica dos personas:\n\n1. Una NOEMÍ tuya: alguien que necesita compañía sostenida y a quien tú puedes acompañar como Rut. Hazle una visita real, no virtual. Quédate.\n\n2. Un BOOZ tuyo: alguien que te ha sostenido en alguna de tus pobrezas. Agradécele explícitamente — carta, llamada, presencia.\n\nNota qué sientes después de cada gesto.',
    preguntas: [
      '¿A quién en mi vida he acompañado cuando todos los demás se han ido?',
      '¿Quién me ha acompañado a mí en mis "Moab" personales?',
      '¿Tengo una comunidad real de fe, o estoy creciendo en solitario?',
      '¿De qué "extranjero" — alguien fuera de mi círculo — he aprendido más de Dios?',
      '¿Qué Noemí estoy descuidando ahora?',
      '¿Qué Booz tengo pendiente de agradecer?'
    ],
    salmoNombre: 'Salmo 133 / 1 Cor 13',
    salmo: '¡Qué bueno y qué dulce es que los hermanos vivan unidos!\nEs un óleo perfumado sobre la cabeza, que baja por la barba, la barba de Aarón.\nEs un rocío del Hermón que baja sobre los montes de Sión.\nPorque allí da el Señor la bendición: la vida eterna.\n\n«Aunque hablara las lenguas de los hombres y de los ángeles, si no tengo amor, soy bronce que suena o címbalo que retumba.» (1 Cor 13,1)',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'jose',
    numero: 8,
    nombre: 'José',
    subtitulo: 'Crecer socialmente: servir al pueblo',
    versiculo: 'Lo que ustedes pensaron para mal, Dios lo convirtió en bien. — Gen 50,20',
    color: '#8a5040',
    pdfPage: 70,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Ayúdame, Padre, a compartir con tu pueblo lo que soy y lo que tengo, para que mis acciones sean pan de vida para los demás. Hazme luchar con tu pueblo para hacer tu voluntad. Te lo pido por tu Hijo, Jesucristo. Amén.',
    introduccion: 'Después del crecimiento personal (Pablo) y del comunitario (Rut), viene el tercer crecimiento: el SOCIAL. Es la salida del círculo íntimo hacia la responsabilidad por el pueblo entero — el uso de los talentos, los recursos y el poder al servicio de todos, especialmente de los más vulnerables.\n\nNo se llega aquí por casualidad. La mayoría de la gente, una vez resuelto su crecimiento personal y construido su círculo de afectos, se detiene. Crecer socialmente es lo que distingue al cristiano adulto del cristiano cómodo. Y, sorprendentemente, ese tercer crecimiento es el que da a los dos primeros su sentido pleno.\n\nJosé, el hijo número once de Jacob, vendido por sus hermanos como esclavo a Egipto, llegó a ser segundo en el imperio. Tuvo poder absoluto, riqueza, prestigio. Y no usó nada de eso para vengarse, ni para acumular, ni para hundir a sus hermanos cuando llegó la hora. Lo usó para SALVAR — a su familia, a su pueblo, a Egipto entero. Su frase final, dicha a los hermanos que le habían arruinado la juventud, sigue siendo la mejor definición de la espiritualidad social: «Lo que ustedes pensaron para mal, Dios lo convirtió en bien».',
    historia: 'José era el penúltimo hijo de Jacob, hijo de Raquel, la esposa amada. Por eso Jacob lo prefería abiertamente — le regaló una túnica de mangas largas que delataba el favoritismo. Sus diez hermanos mayores lo odiaron.\n\nDe muchacho tuvo dos sueños: en el primero, las gavillas de sus hermanos se inclinaban ante la suya; en el segundo, el sol, la luna y once estrellas se inclinaban ante él. Los contó. El odio creció.\n\nUn día, mientras pastoreaban lejos, los hermanos lo vieron venir. Decidieron matarlo. Rubén intercedió: solo lo echaron a una cisterna seca. Pasó una caravana de mercaderes ismaelitas. Lo vendieron por veinte monedas de plata. Tiñeron su túnica con sangre de cabrito y le dijeron a Jacob que una fiera lo había devorado. Jacob lloró sin consuelo.\n\nEn Egipto, José fue comprado por Putifar, oficial del faraón. Trabajó con honestidad y prosperó. La esposa de Putifar lo deseó; José se negó día tras día; ella lo acusó falsamente de intento de violación. Cárcel.\n\nEn la cárcel, interpretó los sueños del copero y del panadero del faraón. El copero, restituido, lo olvidó dos años. Hasta que el faraón mismo soñó con siete vacas gordas y siete flacas. Nadie podía interpretar. El copero recordó: «Hay un hebreo en la cárcel que sabe…».\n\nLo sacaron. José interpretó: vendrán siete años de abundancia y siete de hambre. Y propuso un plan: nombrar un administrador que recoja un quinto de la cosecha durante los años buenos para distribuirlo en los malos. El faraón lo nombró segundo del reino. Tenía 30 años.\n\nLlegó el hambre. Llegó también a Canaán. Jacob mandó a sus hijos a comprar grano a Egipto. Llegaron ante José y no lo reconocieron. Él sí los reconoció, pero los probó. Pidió que trajeran a Benjamín, el menor. Cuando lo vio, no aguantó: lloró, se descubrió, los abrazó. Les dijo: «No se entristezcan ni se reprochen el haberme vendido. Dios me envió delante de ustedes para preservarles la vida. No fueron ustedes los que me enviaron aquí, sino Dios» (Gen 45,5-8).\n\nTrajeron a Jacob. La familia entera vivió bajo la protección de José en Egipto. Cuando Jacob murió, los hermanos temieron que José se vengara. Vinieron temerosos. José lloró otra vez y les dijo lo definitivo: «No teman. ¿Acaso ocupo yo el lugar de Dios? Ustedes pensaron hacerme mal, pero Dios lo convirtió en bien para hacer lo que hoy se ve: salvar a un pueblo numeroso. No teman; yo los mantendré a ustedes y a sus hijos» (Gen 50,19-21).',
    aplicacion: 'José nos enseña la lógica del crecimiento social cristiano:\n\n1. EL TALENTO ES PARA EL PUEBLO. Los dones que tienes — administración, palabra, dinero, oficio, escucha — no son para tu engrandecimiento. Son para servir. José interpretó sueños no para volverse famoso, sino para salvar gente.\n\n2. EL PODER ES PARA SERVIR. Quien tiene poder y no lo usa para los débiles, lo está malgastando. José tuvo el poder absoluto del imperio en sus manos y lo dirigió a alimentar a quien tenía hambre.\n\n3. EL PERDÓN ES POSIBLE PORQUE DIOS REINTERPRETA LA HISTORIA. José no minimiza el daño que le hicieron. Lo nombra. Pero lo lee dentro de un plan más grande: «Ustedes pensaron mal, Dios lo convirtió en bien». Esa relectura es lo que libera del rencor.\n\n4. SE GANA SENTIDO AL SERVIR. Cuando pones tu vida al servicio del pueblo por amor, te brotan fuerzas, te llega gozo profundo, le encuentras sentido a lo que vives. Es como enamorarse: no se entiende hasta que se prueba.',
    ejercicio: 'Esta semana, elige un talento o recurso concreto que tengas — tiempo, dinero, una habilidad técnica, capacidad de escucha, contactos — y ponlo de manera concreta al servicio de alguien que lo necesite. Que no sea simbólico: que cueste algo.\n\nObserva qué sientes después. Anótalo. Luego pregúntate: ¿qué pasaría si esto no fuera un episodio sino una manera de vivir?',
    preguntas: [
      '¿Cuáles son mis talentos reales — los que reconozco aunque me cueste decirlo?',
      '¿Para qué los estoy usando hoy — para mi engrandecimiento o para el bien del pueblo?',
      '¿Qué poder, por pequeño que sea, tengo en mi entorno — y cómo lo ejerzo?',
      '¿A quién necesito perdonar releyendo la historia como José: "lo pensaron para mal, Dios lo convirtió en bien"?',
      '¿Qué hambre concreta cercana puedo aliviar yo con lo que tengo?',
      '¿Estoy detenido en el crecimiento personal y comunitario sin dar el salto al social?'
    ],
    salmoNombre: 'Magníficat (Lc 1,46-55)',
    salmo: 'Proclama mi alma la grandeza del Señor, se alegra mi espíritu en Dios mi salvador.\nPorque ha mirado la humildad de su esclava: desde ahora me felicitarán todas las generaciones.\nEl Poderoso ha hecho obras grandes en mí, su nombre es santo.\nSu misericordia llega a sus fieles de generación en generación.\nDespliega la fuerza de su brazo, dispersa a los soberbios de corazón.\nDerriba del trono a los poderosos y enaltece a los humildes.\nA los hambrientos los colma de bienes, y a los ricos los despide vacíos.\nAuxilia a Israel, su siervo, acordándose de su misericordia.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'moises',
    numero: 9,
    nombre: 'Moisés',
    subtitulo: 'Crecer espiritualmente: del ideal al Dios vivo',
    versiculo: 'Como ciervo sediento en busca de un río, así, Dios mío, te busco a ti. — Salmo 42',
    color: '#4a7050',
    pdfPage: 80,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Como ciervo sediento en busca de un río, así, Dios mío, te busco a ti. Tengo sed de ti, Dios de la vida, pues sólo tú llenas mi vida de alegría. ¿Por qué voy a desanimarme? ¿Por qué voy a estar preocupado? Mi esperanza he puesto en Dios, y sólo a Él seguiré. Envíame tu luz y tu verdad y enséñame el camino que me llevará a ti. (Salmo 42)',
    introduccion: 'El cuarto crecimiento es el espiritual propiamente dicho. Es el más sutil de todos, porque es el que más fácilmente se confunde con su falsificación: la religiosidad ideológica.\n\nUna persona puede tener mucho conocimiento religioso, mucha disciplina espiritual, mucha actividad eclesial, y estar espiritualmente seca. ¿Por qué? Porque ha sustituido al DIOS VIVO por una IDEA de Dios. La idea es manejable: la entiendes, la defiendes, la usas para juzgar a otros. El Dios vivo no: te interpela, te cambia, te lleva a donde no querías ir.\n\nMoisés es el modelo del paso del ideal al Dios vivo. Pasó cuarenta años creyéndose libertador y peleándose con la realidad. Otros cuarenta en el desierto siendo simple pastor, dejando que se le cayeran las ideas. Y solo entonces, frente a una zarza que ardía sin consumirse, conoció al Dios que se nombra a sí mismo: «Yo soy el que soy» — el Dios que es PRESENCIA, no concepto.\n\nA partir de ahí, ya no obedeció a una idea de Dios; obedeció a un Dios que actuaba en la historia concreta de su pueblo esclavo. Esa es la diferencia.',
    historia: 'Moisés nació en Egipto cuando los israelitas eran esclavos y el faraón había ordenado matar a todos los varones hebreos recién nacidos. Su madre lo escondió tres meses, y cuando ya no pudo, lo puso en una canastilla de junco impermeabilizada y la dejó entre los cañaverales del Nilo. La hija del faraón lo encontró bañándose, se compadeció y lo adoptó. Lo llamó Moisés, «el sacado de las aguas».\n\nCreció en el palacio como egipcio. Pero sabía de su origen. Un día vio a un capataz egipcio golpeando a un hebreo. Miró a un lado, miró al otro, y mató al egipcio. Lo enterró en la arena. Al día siguiente, dos hebreos peleaban; intentó separarlos. Uno le dijo: «¿Quién te ha hecho jefe nuestro? ¿Quieres matarme también a mí como mataste al egipcio?» Lo sabían. Huyó al desierto de Madián.\n\nSe casó con Séfora, hija del sacerdote Jetró. Fue pastor cuarenta años. Una vida entera obedeciendo a las ovejas. Su sueño de libertador parecía borrado.\n\nUn día llevó el rebaño hasta el monte Horeb. Vio una zarza que ardía sin consumirse. Se acercó. Y oyó: «Moisés, Moisés. Quítate las sandalias, porque el lugar que pisas es tierra santa. Yo soy el Dios de tu padre, el Dios de Abraham, el Dios de Isaac y el Dios de Jacob. He visto la opresión de mi pueblo en Egipto, he oído sus gritos ante los opresores, conozco sus sufrimientos. Voy a bajar a librarlo. Anda, te envío al faraón» (Ex 3,1-10).\n\nMoisés respondió con miedos: «¿Quién soy yo para ir al faraón?» «¿Y si no me creen, si me dicen: cómo se llama tu Dios?» «No sé hablar.» Dios le respondió a cada uno. Le dio su nombre: «Yo soy el que soy» — YHWH. Le dio señales. Le dio a Aarón como vocero.\n\nMoisés volvió a Egipto. Confrontó al faraón diez veces. Vinieron las plagas. Salió con el pueblo. Cruzó el mar. Pasó cuarenta años en el desierto guiando a un pueblo que se quejaba todo el tiempo. Recibió la Ley en el Sinaí. No entró en la tierra prometida — la vio desde lejos, en el monte Nebo, antes de morir. Pero su pueblo entró.\n\nMoisés no fue grande por sus dones. Fue grande porque dejó que Dios fuera Dios — un Dios vivo, que actúa, que tiene rostro y nombre, no una idea bonita.',
    aplicacion: 'Cuatro modos de leer la Biblia (y de vivir la fe):\n\n• DOÑA RELIGIÓN la lee como ideología. Importa la doctrina correcta. Resultado: rigidez.\n• DOÑA SUSTO la lee con miedo a Dios. Importa no fallar. Resultado: angustia.\n• DOÑA SABE-TODO la lee para tener razón. Importa ganar discusiones. Resultado: arrogancia.\n• DOÑA LUZ la lee para descubrir cómo Dios está actuando hoy en su vida y en su pueblo. Importa el encuentro. Resultado: crecimiento real.\n\nLas tres primeras manejan IDEAS de Dios. La cuarta busca al DIOS VIVO. Solo la cuarta crece espiritualmente.\n\nMoisés enseña tres pasos:\n\n1. DIOS LLAMA DESDE LA VIDA, no desde una idea. Tu zarza ardiente está en lo concreto: en lo que hoy te duele, te alegra, te interpela.\n\n2. DIOS LIBERA. Donde hay opresión y luchas por liberarte de algo que te oprime, ahí Dios está actuando. La fe que no libera no es bíblica.\n\n3. SOLO DIOS HACE CRECER. Tus esfuerzos importan, pero el crecimiento real es obra suya. Tu papel es no estorbar.',
    ejercicio: 'Esta semana, elige un pasaje del Evangelio de Lucas o de Marcos. Léelo cada día con esta pregunta: ¿cómo está Dios actuando AHORA en mi vida del mismo modo en que actuó en este pasaje?\n\nNo busques ideas. No busques moralejas. Busca acción concreta. Ejemplo: si lees la curación del ciego, pregúntate ¿qué ceguera mía está sanando ahora? Si lees la multiplicación de panes, ¿qué pequeño pan mío está alcanzando para más de lo que pensaba?\n\nLleva un cuaderno. Una semana de esto cambia mucho.',
    preguntas: [
      '¿Cuál de las cuatro Doñas vive más en mí — Religión, Susto, Sabe-todo o Luz?',
      '¿Cuál es mi "zarza ardiente" actual — la realidad concreta donde Dios me está hablando?',
      '¿Confundo el Dios vivo con una idea de Dios que ya no me interpela?',
      '¿De qué "Egipto" — qué opresión interna o externa — me está sacando Dios ahora?',
      '¿Qué Tierra Prometida estoy esperando que se me dé regalada y no estoy caminando?',
      '¿Quién es Aarón en mi vida — la persona que Dios me da para acompañarme?'
    ],
    salmoNombre: 'Salmo 42 / Salmo 136 (selección)',
    salmo: 'Como busca la cierva corrientes de agua, así mi alma te busca a ti, Dios mío.\nMi alma tiene sed del Dios vivo: ¿cuándo entraré a ver el rostro de Dios?\nMis lágrimas son mi pan de día y de noche, mientras me dicen sin cesar: «¿Dónde está tu Dios?»\nRecuerdo otros tiempos y desahogo mi alma: cómo iba con la multitud, los conducía hacia la casa de Dios entre cantos de júbilo.\n¿Por qué te acongojas, alma mía, por qué te me turbas? Espera en Dios, que volveré a alabarlo: «Salud de mi rostro, Dios mío».',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  },

  {
    id: 'jesus',
    numero: 10,
    nombre: 'Jesús',
    subtitulo: 'Amistad personal con Dios',
    versiculo: 'Ya no los llamo siervos, los llamo amigos. — Jn 15,15',
    color: '#c89030',
    pdfPage: 90,
    entrada: 'En el nombre del Padre y del Hijo y del Espíritu Santo. Amén.',
    oracionInicial: 'Jesús, ayúdame a conocerte internamente para que más pueda yo amarte y seguirte. (Oración de san Ignacio de Loyola)',
    introduccion: 'Después de los nueve caminos, llega el último — y el que da sentido a todos los demás. La fe cristiana, en su corazón, no es una doctrina ni un código moral ni un sistema espiritual. Es una AMISTAD. Una amistad personal, real, recíproca, con Jesús.\n\nEntre amigos, todo es posible: las exigencias se vuelven gusto, las dificultades se cargan juntos, los silencios pesan menos. Entre quienes no son amigos, hasta lo mínimo se vuelve carga. Esa es la diferencia entre una vida cristiana viva y una vida religiosa cansada.\n\nJesús no buscó simples seguidores. Buscó amigos. Tomó la iniciativa: «No me eligieron ustedes a mí; fui yo quien los eligió a ustedes» (Jn 15,16). Los defendió cuando otros los criticaban. Los necesitó: en Getsemaní pidió que se quedaran cerca. Se dejó cambiar por ellos: la madre lo empujó a hacer su primer milagro antes de tiempo, la cananea lo hizo recapacitar y curar a su hija. Su amistad con Pedro tuvo crisis, traición, perdón, restauración — como toda amistad verdadera. Y, al final, ambos dieron la vida el uno por el otro.\n\nEste último camino se vive durante toda la vida. Es donde desemboca el discernimiento, la oración, la comunidad y el servicio. Y, sobre todo, es donde se aprende que Dios ya no es un Tú lejano, sino un amigo cercano cuyo nombre tienes en la boca.',
    historia: 'Jesús de Nazaret eligió personalmente a doce hombres para que estuvieran con él. La frase es importante: estuvieran CON ÉL. Antes de enviarlos, antes de que predicaran o curaran, los quería con él. La amistad fue lo primero.\n\nLos defendió. Cuando los fariseos lo criticaron por comer en casa de Mateo el cobrador con publicanos y pecadores — lo peor de la sociedad religiosa de su época — respondió: «No son los sanos los que necesitan médico, sino los enfermos. No vine a llamar a justos, sino a pecadores» (Mt 9,12-13).\n\nLos necesitó. La noche antes de su muerte, en Getsemaní, llevó a Pedro, Santiago y Juan al borde y les dijo: «Mi alma está triste hasta el punto de morir. Quédense aquí y velen conmigo» (Mt 26,38). Es una de las frases más conmovedoras del Evangelio: el Hijo de Dios pidiéndole compañía a sus amigos en su peor noche.\n\nSe dejó cambiar por ellos. En Caná, la primera vez que aparece en público haciendo algo extraordinario, fue su madre quien lo empujó: «No tienen vino». Él al principio se resistió: «Mujer, todavía no ha llegado mi hora». Pero ella, sin discutir, dijo a los servidores: «Hagan lo que él les diga». Y él, sin más, hizo el milagro (Jn 2,1-11). La cananea le pidió que sanara a su hija; él la probó duramente; ella respondió con humor y fe; él cedió y la curó (Mt 15,21-28). Jesús se dejó tocar por las personas. Eso es amistad.\n\nSu amistad con Pedro es la más larga del Evangelio. Lo eligió primero. Lo nombró roca. Pero Pedro tuvo crisis: lo reprendió cuando Jesús habló de su muerte y se ganó un «¡Apártate de mí, Satanás!». Le juró fidelidad la noche antes de la pasión y lo negó tres veces antes de que cantara el gallo. Lloró amargamente. Después de la resurrección, Jesús lo restauró: tres veces le preguntó «¿Me amas?», las mismas que sus negaciones, y tres veces le confió las ovejas (Jn 21,15-19). Y al final, según la tradición, Pedro murió crucificado en Roma — boca abajo, según pidió, por no creerse digno de morir como su Maestro. Dieron la vida uno por el otro.\n\nEsa es la amistad que Jesús ofrece. No simbólica. Real.',
    aplicacion: 'La oración cristiana es esto: una RELACIÓN entre dos personas — tú y Jesús, que está vivo. No es saber cosas, ni descubrir ideas, ni siquiera buscar paz interior. Es AMARSE.\n\nDos frases clásicas lo dicen todo:\n\n• Santa Teresa: «Orar no es pensar mucho, sino amar mucho.»\n• San Ignacio: «El amor se debe poner más en las obras que en las palabras.»\n\nLa prueba de que tu oración es de verdad: que te impulsa a actuar como Jesús quiere. Si solo te deja sintiéndote bien pero no cambia cómo tratas a la gente, no era oración.\n\nCUATRO CONSEJOS para que tu oración sea amistad real:\n\n1. CONÓCELO. Lee el Evangelio despacio, todos los días, aunque sea un poco. No para "estudiar"; para conocer a alguien.\n\n2. BÚSCALO VIVO. Está actuando ahora en tu vida y en tu pueblo. Detéctalo en lo que pasa hoy.\n\n3. HAZ CON ÉL LA VOLUNTAD DEL PADRE. La amistad se sostiene en la causa común, no solo en la conversación.\n\n4. CUIDA TIEMPOS, LUGARES Y MÉTODOS. Sencillos, sostenibles, tuyos. Diez minutos diarios fieles valen más que dos horas el domingo.',
    ejercicio: 'Esta semana, dedica al menos diez minutos diarios a estar a solas con Jesús. No para pedir cosas, no para "pensar". Solo para estar con un amigo.\n\nEstructura sugerida:\n• Un minuto: ponerte en presencia. Respira. Recuerda que él te mira con cariño.\n• Cinco minutos: lee despacio un trozo del Evangelio (sugerencia para esta semana: Jn 15).\n• Tres minutos: dile lo que te haya tocado. Como a un amigo.\n• Un minuto: agradece y di el Padre Nuestro.\n\nAl final de la semana mira: ¿cómo está la amistad?',
    preguntas: [
      '¿Es Jesús, hoy, un amigo real para mí, o solo un personaje religioso?',
      '¿Qué momentos de mi vida cristiana han sido conversaciones reales con él, no monólogos míos?',
      '¿Le doy a esta amistad el tiempo que le doy a mis otras amistades importantes?',
      '¿En qué se nota en cómo trato a la gente que soy amigo de Jesús?',
      '¿Tengo crisis con él que evito hablar — como Pedro tras la negación?',
      '¿Qué quiero pedirle hoy que me deje conocerlo internamente?'
    ],
    salmoNombre: 'Salmo 145 (selección)',
    salmo: 'El Señor es clemente y misericordioso, lento a la cólera y rico en piedad.\nEl Señor es bueno con todos, su ternura abarca todas sus obras.\nQue todas tus obras te den gracias, Señor, que te bendigan tus fieles.\nEl Señor es fiel a sus palabras, bondadoso en todas sus acciones.\nEl Señor sostiene a los que van a caer, endereza a los que ya se doblan.\nEstá cerca el Señor de los que lo invocan, de los que lo invocan sinceramente.\nCumple los deseos de los que lo temen, escucha sus gritos y los salva.',
    oracionFinal: 'Que el Señor nos bendiga, que nos dé las fuerzas para seguir su llamado y que nos lleve a una vida plena tal como nos lo había prometido desde los tiempos de Abraham hasta ahora. Amén.'
  }
];

// Sentimientos: 21 emociones agrupadas por familia
window.SENTIMIENTOS = [
  { nombre: 'Paz', emoji: '☮️', familia: 'positivo' },
  { nombre: 'Alegría', emoji: '🌞', familia: 'positivo' },
  { nombre: 'Gratitud', emoji: '🌿', familia: 'positivo' },
  { nombre: 'Esperanza', emoji: '✨', familia: 'positivo' },
  { nombre: 'Amor', emoji: '❤️', familia: 'positivo' },
  { nombre: 'Confianza', emoji: '🕊️', familia: 'positivo' },
  { nombre: 'Entusiasmo', emoji: '🔥', familia: 'positivo' },
  { nombre: 'Nostalgia', emoji: '🍂', familia: 'mixto' },
  { nombre: 'Cansancio', emoji: '🌫️', familia: 'mixto' },
  { nombre: 'Confusión', emoji: '🌀', familia: 'mixto' },
  { nombre: 'Anhelo', emoji: '🌙', familia: 'mixto' },
  { nombre: 'Inquietud', emoji: '🪶', familia: 'mixto' },
  { nombre: 'Vacío', emoji: '◯', familia: 'mixto' },
  { nombre: 'Miedo', emoji: '🌑', familia: 'negativo' },
  { nombre: 'Tristeza', emoji: '💧', familia: 'negativo' },
  { nombre: 'Enojo', emoji: '⚡', familia: 'negativo' },
  { nombre: 'Ansiedad', emoji: '🌊', familia: 'negativo' },
  { nombre: 'Culpa', emoji: '🪨', familia: 'negativo' },
  { nombre: 'Soledad', emoji: '🕯️', familia: 'negativo' },
  { nombre: 'Frustración', emoji: '⛓️', familia: 'negativo' },
  { nombre: 'Desánimo', emoji: '🍃', familia: 'negativo' }
];

// Reglas de discernimiento (Elías + Ignacio)
window.REGLAS_ELIAS = [
  { num: 1, titulo: 'Dos espíritus actúan en ti', texto: 'El Espíritu de Dios trae vida, paz, amor, libertad. El espíritu del mal trae desesperación, miedo, agitación.' },
  { num: 2, titulo: 'Si vas por buen camino', texto: 'El espíritu malo te agita, te desanima, te llena de dudas. El Espíritu Bueno te confirma con paz, valor y ánimo.' },
  { num: 3, titulo: 'Si vas por mal camino', texto: 'Es al revés: el espíritu malo te calma con falsa tranquilidad. El Espíritu Bueno te causa inquietud para que cambies.' },
  { num: 4, titulo: 'La consolación viene de Dios', texto: 'Paz honda, alegría serena, lágrimas de gratitud, ganas de servir.' },
  { num: 5, titulo: 'En desolación, no decidas', texto: 'Tristeza, agitación, desesperanza vienen del enemigo. NUNCA tomes decisiones nuevas en desolación. Aguanta, ora más, pide ayuda.' },
  { num: 6, titulo: 'Dios habla suave', texto: 'No en el viento, ni en el terremoto, ni en el fuego — sino en un susurro. Si una voz te empuja con prisa o ansiedad, no es de Dios.' }
];
