// Canvas Integral de Integración de Sombras (15)
window.SOMBRAS = [
  { id: 1, name: "Salvador Espiritual", que: "Creer que tu valor depende de salvar a todos. Te da culpa avanzar si otros no avanzan.", canal: "Convertir tu impulso de salvar en servir desde la libertad, no desde el sacrificio.", preguntas: ["¿A quién quiero salvar realmente?", "¿Estoy ayudando o pagando una deuda emocional?", "¿Qué pasaría si primero me salvo yo?"], decreto: "Sirvo desde mi plenitud, no desde mi sacrificio.", ancla: "Tócate el pecho (mano derecha) y di: 'Primero yo me lleno, luego sirvo.'", oracion: "Señor Dios, ordéname por dentro para que mi servicio nazca del amor y no del miedo. Guíame a servir sin perderme.", objetivo: "1 acto diario donde te elijas a ti antes que a otros." },
  { id: 2, name: "Soldado Perfecto", que: "Creer que fallar te quita valor.", canal: "Usar la disciplina militar como estructura, no como castigo.", preguntas: ["¿Qué espero de mí que ni Dios me exige?", "¿Es disciplina o miedo a decepcionar?", "¿Qué pasaría si fallara hoy?"], decreto: "Mi valor no depende de mi perfección.", ancla: "Aprieta firme tu puño y suéltalo: 'Libero la exigencia. Re-emprendo desde la humildad.'", oracion: "Dios, dame la gracia de aceptar mi humanidad y aprender sin castigarme.", objetivo: "Permitirte 1 error diario sin castigarte." },
  { id: 3, name: "Hijo Responsable", que: "Creer que debes cargar la economía y destino familiar tú solo.", canal: "Transformar la carga en liderazgo consciente.", preguntas: ["¿Estoy sanando o cargando?", "¿Esta responsabilidad me la dieron o me la puse?", "¿Qué parte de mi familia no depende de mí?"], decreto: "Honro a mi familia sin cargar sus destinos.", ancla: "Toca tus hombros: 'Suelto el peso que no me pertenece.'", oracion: "Dios, enséñame a liderar sin cargar. Hazme instrumento de claridad, no de peso.", objetivo: "Delegar o soltar una responsabilidad innecesaria hoy." },
  { id: 4, name: "El Elegido", que: "Sentir que tu misión es tan grande que cualquier error 'ofende a Dios'.", canal: "Ver tu propósito como un camino, no un examen.", preguntas: ["¿Quién dijo que Dios se ofende con mis avances?", "¿Qué parte de mi misión se aclara cuando me muevo?", "¿Qué haría si supiera que Dios ya aprobó mi próximo paso?"], decreto: "Mi propósito es un camino, no un examen.", ancla: "Mira al cielo 3 segundos: 'Mi propósito se revela al moverme.'", oracion: "Dios, libérame de la imagen del juez para que pueda servirte como hijo, no como esclavo del miedo.", objetivo: "1 paso pequeño hoy, sin esperar señal perfecta." },
  { id: 5, name: "Autosabotador Espiritual", que: "Cada vez que estás a punto de lograr algo, aparece culpa, duda o un freno.", canal: "Reconocer el sabotaje como señal de crecimiento, no de error.", preguntas: ["¿Qué se removería si esto sí me funcionara?", "¿De qué identidad antigua me cuesta despedirme?", "¿Qué temo que cambie si recibo lo bueno?"], decreto: "El autosabotaje es señal de que estoy creciendo, no de que me equivoco.", ancla: "5-4-3-2-1, paso físico adelante: 'Cuando crezco, el miedo habla. Yo sigo.'", oracion: "Dios, dame valor para recibir sin frenarme. Suelto la culpa de avanzar.", objetivo: "Hoy ejecuta una acción que te dé miedo recibir." },
  { id: 6, name: "No Merezco Aún", que: "Creer que debes pagar más, sufrir más o demostrar más antes de recibir.", canal: "Recibir como acto de fe, no de mérito.", preguntas: ["¿Quién me dijo que no soy digno todavía?", "¿Qué se siente cuando recibo sin justificarme?", "¿Qué se abre si acepto lo bueno hoy?"], decreto: "Soy digno de lo bueno ahora. La gracia se recibe, no se gana con sufrimiento.", ancla: "Mano al pecho: 'Acepto lo bueno. Soy digno ahora, no después.'", oracion: "Dios, enséñame a recibir como un hijo amado, no como un mendigo.", objetivo: "Cuando hoy te llegue algo bueno, di solo: 'Gracias, lo recibo.'" },
  { id: 7, name: "Comparación", que: "Medir tu valor por la velocidad de otros.", canal: "Convertir la comparación en aprendizaje y sin envidia.", preguntas: ["¿Quién me dijo que su tiempo es el mío?", "¿Qué admiro de esa persona que ya está en mí?", "¿Qué dejaría de hacer si no me comparara?"], decreto: "Mi camino es único. Mi velocidad es perfecta para mi historia.", ancla: "Toca tu frente: 'Mi tiempo es Suyo. No el de ellos.'", oracion: "Dios, sana mi mirada para ver el camino del otro como inspiración, no como amenaza.", objetivo: "Felicita honestamente a alguien hoy sin compararte." },
  { id: 8, name: "Aprobación Externa", que: "Buscar validación constante en likes, comentarios o aprobaciones familiares.", canal: "Volver a la voz interna como única autoridad.", preguntas: ["¿De quién busco aprobación que ya no me corresponde?", "¿Qué cambiaría si nadie me viera?", "¿Quién soy cuando nadie aplaude?"], decreto: "La única aprobación que necesito es la mía y la de Dios.", ancla: "Pon mano izquierda en abdomen: 'Yo me apruebo. Dios me valida.'", oracion: "Dios, libérame del aplauso humano. Que tu mirada me baste.", objetivo: "Hoy haz algo bien sin contárselo a nadie." },
  { id: 9, name: "Control Excesivo", que: "Creer que si no controlas todo, todo se cae.", canal: "Soltar control donde solo necesitas confianza.", preguntas: ["¿Qué pasaría si soltara este control hoy?", "¿Qué me da seguridad real, control o fe?", "¿Qué quiero controlar que no es mío?"], decreto: "Suelto lo que no puedo controlar. Confío en lo que sostiene todo.", ancla: "Manos abiertas hacia el cielo: 'Suelto. Suelto. Suelto.'", oracion: "Dios, dame paz para soltar lo que no me toca y fuerza para hacer lo que sí.", objetivo: "Delega o suelta una decisión hoy. No la cargues solo." },
  { id: 10, name: "Mártir", que: "Creer que mereces más cuanto más sufres.", canal: "Construir desde la abundancia, no desde el dolor heroico.", preguntas: ["¿Qué dolor cargo que ya no me sirve?", "¿Estoy sirviendo o sangrando?", "¿Qué pasaría si dejara de cargar?"], decreto: "Sufrir no me hace más santo. Servir desde la plenitud sí.", ancla: "Suelta los hombros: 'Mi cruz no es el peso del mundo. Es la mía y suficiente.'", oracion: "Dios, libérame de cargar lo que no me toca para servir mejor lo que sí.", objetivo: "Hoy elige descanso sin culpa." },
  { id: 11, name: "Procrastinador Místico", que: "Esperar señales 'divinas' para no actuar.", canal: "Mover el cuerpo aunque la cabeza dude.", preguntas: ["¿Qué señal espero que no llegará?", "¿Qué acción concreta evito?", "¿Qué pasaría si actúo antes de la certeza?"], decreto: "La señal de Dios viene en movimiento.", ancla: "5-4-3-2-1, ejecuta una acción mínima.", oracion: "Dios, sácame de la espera espiritual y dame valentía para empezar.", objetivo: "Hoy haz algo que llevas días posponiendo. Sin justificación." },
  { id: 12, name: "Soberbia Disfrazada de Humildad", que: "Sentirte 'más consciente' que otros y aislarte.", canal: "Bajar al barro de la humanidad común.", preguntas: ["¿A quién separo de mí por sentirme superior?", "¿Qué me cuesta admitir que aún aprendo?", "¿Qué se sanaría si me mostrara más vulnerable?"], decreto: "No soy mejor, soy diferente. Mi conciencia me da responsabilidad de servir más.", ancla: "Manos juntas en oración: 'Bajo. Aprendo. Sirvo.'", oracion: "Dios, mantenme humilde aún en la luz que me regalas.", objetivo: "Hoy escucha a alguien sin juzgar ni corregir." },
  { id: 13, name: "Niño Herido", que: "Reaccionar como niño cuando algo no sale como esperabas.", canal: "Abrazar al niño y liderar como adulto consciente.", preguntas: ["¿Qué edad tiene la voz que ahora me reclama?", "¿Qué necesitaba ese niño que no recibió?", "¿Qué le diría yo, hoy adulto?"], decreto: "Veo al niño. Lo abrazo. Yo lidero ahora.", ancla: "Mano en el pecho 5 segundos en silencio.", oracion: "Dios, sana al niño en mí para que el adulto pueda servirte sin dolor.", objetivo: "Hoy responde con calma donde antes habrías reaccionado." },
  { id: 14, name: "Adicto a la Intensidad", que: "Buscar drama, urgencia o crisis para sentirte vivo.", canal: "Aprender a sostener la calma sin aburrirte.", preguntas: ["¿Por qué creo que la calma es aburrida?", "¿Qué evito sentir cuando todo está tranquilo?", "¿Qué pasaría si nada urgente apareciera?"], decreto: "La calma no es vacío. Es el suelo donde construyo.", ancla: "Inhala 4, sostén 4, exhala 6. Tres veces.", oracion: "Dios, enséñame que tu paz es más poderosa que cualquier intensidad.", objetivo: "Hoy resiste el impulso de generar drama o urgencia falsa." },
  { id: 15, name: "Eterno Aprendiz", que: "Estudiar infinitamente para no exponerte a vender o publicar.", canal: "Convertir el conocimiento en acción.", preguntas: ["¿Cuánto sé que aún no aplico?", "¿Qué temo que pase si me expongo?", "¿Qué cambiaría si actuara con lo que ya sé?"], decreto: "Lo que ya sé basta para empezar. El resto se aprende ejecutando.", ancla: "Cierra el libro o el curso. Abre el documento de acción.", oracion: "Dios, dame el coraje de aplicar lo que ya me regalaste.", objetivo: "Publica, vende o ejecuta hoy con lo que ya sabes." },
];
