// 100 Directivas para Modo Monje — extraídas del manual personal de Alex Mike
window.DIRECTIVAS_MONJE = [
  { id: 1, cat: "Supervivencia y Finanzas", title: "Opera con urgencia, no con desesperación", body: "Reconoce que tu capital es mínimo; la desesperación ahuyenta, pero la urgencia enfocada te hará ejecutar con velocidad." },
  { id: 2, cat: "Supervivencia y Finanzas", title: "Reduce tus gastos al mínimo vital", body: "Vive por debajo de lo que ganas y elimina cualquier gasto superfluo para extender la duración de tus ahorros mientras generas tu primera venta." },
  { id: 3, cat: "Supervivencia y Finanzas", title: "Mata las deudas de consumo", body: "No utilices tarjetas ni adquieras créditos para aparentar un estilo de vida que aún no tienes; hoy debes gastar como pobre y trabajar como constructor." },
  { id: 4, cat: "Supervivencia y Finanzas", title: "Vende inmediatamente", body: "La antesala de la abundancia es la venta; el dinero no es un milagro, es un intercambio de valor." },
  { id: 5, cat: "Supervivencia y Finanzas", title: "Busca flujo de caja rápido (cash flow)", body: "No intentes ahora hacer inversiones de bolsa ni bienes raíces; usa tu tiempo para captar clientes locales y expertos que te paguen iguala mensual o adelanto por tus servicios de IA." },
  { id: 6, cat: "Supervivencia y Finanzas", title: "No cobres barato por tu tiempo, vende soluciones", body: "A tus 'gigantes dormidos' ofréceles transformar su conocimiento en sistema automatizado y cóbrales pago inicial o revenue share." },
  { id: 7, cat: "Supervivencia y Finanzas", title: "Contacta 10 a 20 prospectos al día", body: "El juego inicial es estadístico y de volumen. Encuentra personas con conocimiento pero sin presencia digital." },
  { id: 8, cat: "Supervivencia y Finanzas", title: "Aprende a registrar cada peso", body: "Si no sabes controlar 10,000 MXN, jamás sabrás controlar un millón. La riqueza comienza con la administración microscópica." },
  { id: 9, cat: "Supervivencia y Finanzas", title: "Usa tu carencia como palanca", body: "El dolor de no tener ingreso fijo debe ser tu apalancamiento emocional para destruir la procrastinación." },
  { id: 10, cat: "Supervivencia y Finanzas", title: "El dinero es neutro y abundante", body: "Suelta la idea de que cobrar está mal. Tu labor con la IA aporta valor incalculable que merece remuneración." },

  { id: 11, cat: "Reprogramación Mental", title: "Disuelve tu vieja identidad", body: "El soldado que seguía órdenes estructuradas debe morir; ahora eres el creador total de las reglas y sistemas de tu vida." },
  { id: 12, cat: "Reprogramación Mental", title: "Aniquila el ego y la falsa validación", body: "Deja de buscar que el mundo apruebe tus decisiones; el ego compite, pero el alma crea." },
  { id: 13, cat: "Reprogramación Mental", title: "Asume 100% de responsabilidad", body: "Si te quedas sin dinero, es tu responsabilidad; si triunfas, también. Sal de la postura de víctima para siempre." },
  { id: 14, cat: "Reprogramación Mental", title: "Deja de sobrepensar en bucle", body: "La mente sobrepiensa como mecanismo de defensa para no actuar y evitar el fracaso." },
  { id: 15, cat: "Reprogramación Mental", title: "Declara tu nueva identidad con emoción", body: "Frente al espejo, repite con energía: 'Soy un imán para el dinero, soy creador de abundancia.' Reprograma tu neuroplasticidad." },
  { id: 16, cat: "Reprogramación Mental", title: "Paga el precio del rechazo", body: "El 'no' del prospecto te desensibiliza del miedo y te entrena para sostener la abundancia." },
  { id: 17, cat: "Reprogramación Mental", title: "Transita tu noche oscura del alma", body: "Ese vértigo de haber 'quemado tus barcos' es el proceso en el que las hojas secas caen para mostrar tu esencia." },
  { id: 18, cat: "Reprogramación Mental", title: "Elimina el pensamiento condicionado", body: "Reprograma la mentalidad de pobreza consumiendo libros y contenido exclusivamente de creadores de riqueza." },
  { id: 19, cat: "Reprogramación Mental", title: "Normaliza el éxito extraordinario", body: "Acostúmbrate mentalmente a la idea de ganar miles de dólares al mes hasta que sea ordinario para ti." },
  { id: 20, cat: "Reprogramación Mental", title: "Reencuadra la realidad", body: "Ante cualquier fracaso, no digas 'he fallado'; di 'esto es un entrenamiento que me prepara para sostener millones'." },

  { id: 21, cat: "Salud Física", title: "Duerme 7.5 a 8 horas", body: "El sueño es la fundación: tu cerebro funciona rápido, se limpia de toxinas y tomas mejores decisiones." },
  { id: 22, cat: "Salud Física", title: "Entrena 5 días por semana", body: "Tu fuerza física refleja tu coherencia; el ejercicio quema cortisol y forja resiliencia." },
  { id: 23, cat: "Salud Física", title: "Combina fuerza y cardio", body: "Las pesas combaten la pérdida muscular y estimulan el cerebro; el cardio eleva oxigenación y esperanza de vida." },
  { id: 24, cat: "Salud Física", title: "Exponte al sol temprano", body: "Mira la luz del sol al despertar para regular tu ritmo circadiano y llenarte de energía." },
  { id: 25, cat: "Salud Física", title: "Abandona azúcar y ultraprocesados", body: "Esa comida inflama tu cerebro y arruina la claridad mental que necesitas para programar IA y cerrar ventas." },
  { id: 26, cat: "Salud Física", title: "Practica ayuno intermitente", body: "Ventanas de 14–16h sin comer promueven la autofagia y mantienen la mente aguda." },
  { id: 27, cat: "Salud Física", title: "Cena mínimo 3h antes de dormir", body: "Permite que tu cuerpo descanse de verdad y te despiertes con vitalidad." },
  { id: 28, cat: "Salud Física", title: "Exponte al frío intencional", body: "Duchas frías o hielo elevan dopamina y te enseñan a abrazar la incomodidad." },
  { id: 29, cat: "Salud Física", title: "Cero tolerancia a neurotóxicos", body: "Ni una gota de alcohol, tabaco ni drogas. Tu cerebro es la única máquina que genera la riqueza que buscas." },
  { id: 30, cat: "Salud Física", title: "Desexualiza la mente y evita dopamina rápida", body: "Deja la pornografía y el scroll infinito; tu energía vital es el motor para crear." },

  { id: 31, cat: "Espiritual y Emocional", title: "Pon a Dios primero", body: "Comienza tu día entregando tu voluntad: haz lo natural y deja que Él haga lo sobrenatural en los resultados." },
  { id: 32, cat: "Espiritual y Emocional", title: "Medita u ora en la primera hora", body: "No toques el móvil; usa la quietud para bajar revoluciones, conectar con tu esencia y no operar desde el ego." },
  { id: 33, cat: "Espiritual y Emocional", title: "Diario de gratitud nocturno", body: "Escribe 3 cosas por las que estés agradecido; sintoniza tu cerebro hacia abundancia en vez de escasez." },
  { id: 34, cat: "Espiritual y Emocional", title: "Crea Islas de Tiempo", body: "Bloques de 15–20 min diarios de desconexión total para calmar el sistema nervioso." },
  { id: 35, cat: "Espiritual y Emocional", title: "Perdona y libérate de cargas", body: "El perdón no es debilidad: es expansión energética que te quita pesos para correr más rápido." },
  { id: 36, cat: "Espiritual y Emocional", title: "No te valides por dinero ni resultados", body: "El ego busca tener para ser; el alma sabe que ya 'es' y los resultados son consecuencia." },
  { id: 37, cat: "Espiritual y Emocional", title: "Deja todo mejor de cómo lo encontraste", body: "Cada conversación con un cliente: tu misión es aportarle paz y valor incondicional." },
  { id: 38, cat: "Espiritual y Emocional", title: "Corta relaciones tóxicas y pesimistas", body: "Evita conversaciones de queja; el cinismo bloquea tu cerebro y tu avance." },
  { id: 39, cat: "Espiritual y Emocional", title: "Celebra el éxito ajeno", body: "Si envidias la riqueza o al rico, jamás podrás atraerla. Admira a quien factura grandes sumas." },
  { id: 40, cat: "Espiritual y Emocional", title: "No reacciones en automático", body: "Desarrolla el espacio entre el estímulo y tu respuesta. La inteligencia emocional te separa del 99%." },

  { id: 41, cat: "Agencia de IA", title: "Crea un sistema automatizado", body: "Tu objetivo a largo plazo no es ser esclavo de clientes, sino construir un sistema que opere por sí solo." },
  { id: 42, cat: "Agencia de IA", title: "Identifica hitos delegables", body: "Documenta todo tu proceso para pronto delegarlo a otra persona o a la IA." },
  { id: 43, cat: "Agencia de IA", title: "Conviértete en Prompt Engineer maestro", body: "Siendo experto en dictar instrucciones a las IA, ejecutarás el trabajo de 10 personas tú solo." },
  { id: 44, cat: "Agencia de IA", title: "Usa agentes de IA para lo mundano", body: "Que las IA redacten correos, generen copies y estructuren productos para tus clientes." },
  { id: 45, cat: "Agencia de IA", title: "Vende tu humanidad, delega la técnica", body: "La IA hará lo técnico; tus clientes te pagarán por conexión humana, visión, empatía y estrategia." },
  { id: 46, cat: "Agencia de IA", title: "No compitas por precio", body: "Ofrece transformación. Cierra ventas basadas en el valor que el cliente ganará." },
  { id: 47, cat: "Agencia de IA", title: "Comprende el juego de Pareto", body: "Enfócate en el 20% de acciones que generan el 80% de tus ingresos: prospección, ventas, sistemas." },
  { id: 48, cat: "Agencia de IA", title: "Reinvierte inteligentemente", body: "Cuando vengan las primeras ganancias grandes, reinvierte en la empresa: marketing, software, educación." },
  { id: 49, cat: "Agencia de IA", title: "Asume el rechazo como matemática", body: "Cada 'no' te entrena y te acerca estadísticamente al 'sí' que cambiará tu mes." },
  { id: 50, cat: "Agencia de IA", title: "Riesgo pequeño, recompensa grande", body: "Experimentar con tácticas de IA cuesta $0; la recompensa puede ser captar clientes de miles." },

  { id: 51, cat: "Habilidades", title: "Estudia marketing sin descanso", body: "Ser un genio técnico no sirve si nadie te conoce. El marketing es comunicar tu solución al problema del cliente." },
  { id: 52, cat: "Habilidades", title: "Enamórate del cierre de ventas", body: "Toda riqueza entra a través de una venta. No tener miedo a pedir la transacción es fundamental." },
  { id: 53, cat: "Habilidades", title: "Domina oratoria y cámara", body: "Si tú o tus clientes no transmiten su mensaje persuasivamente, la IA no los podrá salvar." },
  { id: 54, cat: "Habilidades", title: "Pensamiento estratégico", body: "Planea la noche anterior y enfócate en máximo 3 tareas prioritarias que muevan la aguja económica." },
  { id: 55, cat: "Habilidades", title: "Haz Deep Work", body: "Bloques de 60–120 minutos sin interrupciones ni redes; ahí crearás valor real y productos de alta calidad." },
  { id: 56, cat: "Habilidades", title: "Resolución de problemas", body: "El emprendimiento te bombardeará obstáculos diarios; el que se rinde al primer fallo regresa al mundo laboral." },
  { id: 57, cat: "Habilidades", title: "No te cases con el cómo", body: "Sé terco con tus metas, flexible con la metodología; si una estrategia falla, cambia rápido a la siguiente." },
  { id: 58, cat: "Habilidades", title: "Sana tu inteligencia financiera", body: "Cuando llegue tu primer ingreso fuerte, no lo quemes en lujos; úsalo para fondear activos." },
  { id: 59, cat: "Habilidades", title: "Invierte en ti mismo", body: "El mejor vehículo financiero eres tú y tus habilidades. Consume libros, cursos y mentorías." },
  { id: 60, cat: "Habilidades", title: "Asume riesgos controlados", body: "Si juegas siempre seguro, estás apostando a la mediocridad absoluta." },

  { id: 61, cat: "Marca Personal", title: "La atención es el activo supremo", body: "Todo el dinero está en captar y retener atención; las redes sociales no son opcionales, son obligatorias." },
  { id: 62, cat: "Marca Personal", title: "Usa ganchos poderosos", body: "Domina los primeros 3 segundos para detener el scroll de la audiencia." },
  { id: 63, cat: "Marca Personal", title: "Construye una Escalera de Valor", body: "Atrae con contenido gratis, capta correos con un lead magnet, ofrece tu programa High Ticket." },
  { id: 64, cat: "Marca Personal", title: "Documenta, no finjas", body: "La gente huele a quien vende humo. Documenta tu proceso real desde tus inicios hasta tu imperio." },
  { id: 65, cat: "Marca Personal", title: "Sé curador de conocimiento", body: "Analiza información compleja sobre IA y hazla digerible para gente común y para tus clientes." },
  { id: 66, cat: "Marca Personal", title: "Crea contenido polarizante", body: "A la gente le gusta ver opiniones que reten lo establecido; sé fiel a tus valores sin miedo a 'cancelaciones'." },
  { id: 67, cat: "Marca Personal", title: "Aprovecha el efecto televisión", body: "Que tu cara se vuelva omnipresente en tu nicho mediante repetición; familiaridad genera confianza." },
  { id: 68, cat: "Marca Personal", title: "Comparte tus secretos sin miedo", body: "Regala el 'qué', vende el 'cómo' o la implementación a través de tu agencia." },
  { id: 69, cat: "Marca Personal", title: "Interactúa auténticamente", body: "Responde con empatía genuina; las relaciones online se traducen en oportunidades offline." },
  { id: 70, cat: "Marca Personal", title: "Crea comunidad", body: "Funda un ecosistema basado en Dios, disciplina y dinero donde los clientes sientan pertenencia profunda." },

  { id: 71, cat: "Entorno y Libertad", title: "Elige un Contexto de Poder", body: "Somos el promedio de la gente con la que nos relacionamos. Únete a grupos que piensen en millones, no escasez." },
  { id: 72, cat: "Entorno y Libertad", title: "Compra proximidad", body: "A la primera oportunidad financiera, invierte en estar en habitaciones donde tú seas 'el más tonto' y aprendas." },
  { id: 73, cat: "Entorno y Libertad", title: "Networking inteligente", body: "Aporta valor antes de pedir favores; reparte ayuda sin esperar beneficio inmediato." },
  { id: 74, cat: "Entorno y Libertad", title: "Diseña la empresa para servir tu vida", body: "Tu meta no es ser tu propio esclavo, sino ganar libertad de espacio para viajar y paz mental." },
  { id: 75, cat: "Entorno y Libertad", title: "Delegación extrema", body: "Emprender es fase 1; ser empresario es fase 2. Contrata gente talentosa para todo lo que no sea tu habilidad fundamental." },
  { id: 76, cat: "Entorno y Libertad", title: "Defiende tu tiempo implacablemente", body: "Aprende a decir 'no' a reuniones improductivas, distracciones y relaciones que no construyen tu futuro." },
  { id: 77, cat: "Entorno y Libertad", title: "Valores anticuados, herramientas futuristas", body: "Principios de honor, infraestructura tecnológica moderna." },
  { id: 78, cat: "Entorno y Libertad", title: "Visualiza sin apegos", body: "Crea visión clara de tu vida libre, pero mantén desapego total a los resultados inmediatos." },
  { id: 79, cat: "Entorno y Libertad", title: "Corta lealtades invisibles", body: "Si tu entorno militar mira mal tu nuevo camino, dales ejemplo en lugar de tratar de convencerlos." },
  { id: 80, cat: "Entorno y Libertad", title: "La felicidad viene del propósito", body: "Si eres miserable construyendo tu marca, serás un miserable con un millón de dólares en el banco." },

  { id: 81, cat: "Geopolítica e IA", title: "Sal de la Matrix moderna", body: "El sistema está diseñado para mantenerte distraído y anestesiado. Sal intencionalmente del juego de consumo vacío." },
  { id: 82, cat: "Geopolítica e IA", title: "El trabajo tradicional muere", body: "La IA automatizará casi todo el trabajo lógico e intelectual. Tú debes ser quien controle a la IA." },
  { id: 83, cat: "Geopolítica e IA", title: "Abraza el colapso fiduciario", body: "Las monedas pierden valor por deuda e inflación; protege tu riqueza con activos intangibles y flujo de caja." },
  { id: 84, cat: "Geopolítica e IA", title: "La sociedad sufre soledad extrema", body: "Usa la creación de comunidad para saciar la sed de pertenencia y contacto genuino." },
  { id: 85, cat: "Geopolítica e IA", title: "Filosofía AI First", body: "Ante cualquier problema operativo o estratégico, tu primera acción es consultarlo o delegarlo a tus agentes de IA." },
  { id: 86, cat: "Geopolítica e IA", title: "La tecnología idiotiza a las masas", body: "Quien no se eduque pasará de usuario a usado. La disciplina emocional será la ventaja competitiva final." },
  { id: 87, cat: "Geopolítica e IA", title: "Las soft skills dominan", body: "Empatía, relaciones, ventas reales y liderazgo no podrán ser reemplazados a mediano plazo." },
  { id: 88, cat: "Geopolítica e IA", title: "Las crisis transfieren riqueza", body: "Cuando veas caídas, guerras o miedo colectivo, los empresarios educados crean y compran. No te refugies en el pánico." },
  { id: 89, cat: "Geopolítica e IA", title: "Tu competencia es global", body: "Diferénciate con tu marca personal única y valores morales sólidos." },
  { id: 90, cat: "Geopolítica e IA", title: "Adelántate a los Agentes Autónomos", body: "El futuro no es chatear; es delegar procesos enteros a sistemas que operan sin tu intervención." },

  { id: 91, cat: "Plenitud", title: "El dinero es recompensa por valor aportado", body: "No pidas dinero a Dios; pide fuerza, sabiduría y visión para aportar valor masivo a la humanidad." },
  { id: 92, cat: "Plenitud", title: "Reafirma tu propósito diario", body: "Tu proyecto de potenciar 'gigantes dormidos' con IA no es para llenar bolsillos, es para multiplicar un mensaje que cambia vidas." },
  { id: 93, cat: "Plenitud", title: "Entiende la abundancia espiritual", body: "Cuando reconoces que la paz se experimenta en el presente sin un centavo más, la riqueza gravita hacia ti sin resistencia." },
  { id: 94, cat: "Plenitud", title: "Vive como Millonario Consciente", body: "Identidad donde eres abundante en lo económico y en tu coherencia: salud, tiempo y personas que amas." },
  { id: 95, cat: "Plenitud", title: "Renuncia al sacrificio, abraza la excelencia", body: "Sacrificarte opera desde la insuficiencia; hacerlo con excelencia es servir sin depender del fruto final." },
  { id: 96, cat: "Plenitud", title: "Sé líder espiritual de tus clientes", body: "Guíalos no solo en lo técnico; dales orden y coherencia para que sus marcas representen integridad real." },
  { id: 97, cat: "Plenitud", title: "Honra cada etapa con paciencia agresiva", body: "Sé agresivo en tus hábitos diarios; mantén paciencia cósmica con el ritmo al que llegarán las ventas grandes." },
  { id: 98, cat: "Plenitud", title: "Perdona tu pasado y tus fallas", body: "En el camino de cero a millones habrá errores inevitables. Perdónate para no quedar atrapado en culpa." },
  { id: 99, cat: "Plenitud", title: "Construye legado, no patrimonio", body: "Lo que sostiene tu vida no es lo que acumulas, sino lo que dejas: comunidad, formación, fe heredada." },
  { id: 100, cat: "Plenitud", title: "Cierra el día desde la gratitud", body: "Antes de dormir, agradece tres cosas y pon todo en manos de Dios. La noche es para cerrar, no para juzgar." },
];

window.MONJE_CATEGORIES = [
  "Supervivencia y Finanzas", "Reprogramación Mental", "Salud Física",
  "Espiritual y Emocional", "Agencia de IA", "Habilidades",
  "Marca Personal", "Entorno y Libertad", "Geopolítica e IA", "Plenitud"
];
